# Generated by Django 4.2.3 on 2023-11-02 10:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenancelist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancedevice',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='maintenancelist.maintenancedevicetype'),
        ),
        migrations.AlterField(
            model_name='maintenancedevice',
            name='updatedAt',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Updated at'),
        ),
    ]
