# Generated by Django 4.2.3 on 2023-11-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenancelist', '0002_alter_maintenancedevice_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancedevice',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Réference'),
        ),
    ]
