# Generated by Django 4.2.3 on 2023-11-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenancelist', '0003_alter_maintenancedevice_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancedevice',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
