# Generated by Django 4.2.3 on 2023-11-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenancelist', '0004_alter_maintenancedevice_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceWidgetContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
