# Generated by Django 4.2.3 on 2023-12-05 08:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenancelist', '0005_maintenancewidgetcontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancedevice',
            name='isConform',
        ),
        migrations.RemoveField(
            model_name='maintenancedevice',
            name='lastMaintenance',
        ),
        migrations.RemoveField(
            model_name='maintenancedevice',
            name='maintainer',
        ),
        migrations.RemoveField(
            model_name='maintenancedevice',
            name='report',
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('makedAt', models.DateTimeField(default=datetime.datetime.now, verbose_name='Created at')),
                ('isConform', models.BooleanField(verbose_name='Device is conform after control')),
                ('report', models.CharField(blank=True, max_length=150, null=True, verbose_name='report url join')),
                ('maintainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('maintenanceDevice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenancelist.maintenancedevice')),
            ],
        ),
    ]
