# Generated by Django 4.2.8 on 2024-01-12 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenancelist', '0007_alter_maintenance_options_alter_maintenance_makedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancedevice',
            name='description',
            field=models.TextField(blank=True, max_length=2500, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='maintenancedevice',
            name='locate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Device location'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenanceDevice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenancelist.maintenancedevice', verbose_name='Select device'),
        ),
        migrations.AlterField(
            model_name='maintenancedevice',
            name='period',
            field=models.CharField(choices=[('every month', 'every month'), ('each 3 months', 'each 3 months'), ('each 4 months', 'each 4 months'), ('each 6 months', 'each 6 months'), ('each year', 'each year'), ('every 2 years', 'every 2 years')], max_length=50, verbose_name='Select maintenance period'),
        ),
    ]
